### Creating Tensors

In [1]:
import tensorflow as tf
tf.InteractiveSession()

In [2]:
a = tf.zeros(4)
a.eval()

array([ 0.,  0.,  0.,  0.], dtype=float32)

In [3]:
b = tf.ones(3)
b.eval()

array([ 1.,  1.,  1.], dtype=float32)

In [4]:
c = tf.zeros((2,3))
c.eval()

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]], dtype=float32)

In [5]:
d = tf.fill((2, 2), value=5.)
d.eval()

array([[ 5.,  5.],
       [ 5.,  5.]], dtype=float32)

In [6]:
e = tf.constant(3)
e.eval()

3

In [7]:
f = tf.random_normal((2, 5), mean=0, stddev=1)
f.eval()

array([[-0.32178155, -0.13769928,  1.76888704, -0.11637106,  0.7682988 ],
       [ 0.55621827, -0.63643867, -0.03395032, -1.615574  ,  0.41012686]], dtype=float32)

In [8]:
g = tf.truncated_normal((2, 5), mean=0, stddev=1)
g.eval()

array([[-0.41004425, -1.14099157,  0.10689034, -0.41292939, -0.24922079],
       [-0.91451097,  0.00266269,  1.14489973,  0.3676908 ,  0.79099864]], dtype=float32)

In [9]:
h = tf.random_uniform((2, 2), minval=-2, maxval=2)
h.eval()

array([[-0.45714521, -1.34385109],
       [ 1.47557926, -0.29063511]], dtype=float32)

In [10]:
i = tf.eye(4)
i.eval()

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]], dtype=float32)

In [11]:
j = tf.diag([1., 2., 3.])
j.eval()

array([[ 1.,  0.,  0.],
       [ 0.,  2.,  0.],
       [ 0.,  0.,  3.]], dtype=float32)

### Operating on Tensors

In [12]:
c.eval()

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]], dtype=float32)

In [13]:
ct = tf.matrix_transpose(c)
ct.eval()

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]], dtype=float32)

In [14]:
d.eval()

array([[ 5.,  5.],
       [ 5.,  5.]], dtype=float32)

In [15]:
h.eval()

array([[-1.6428051 ,  0.63717556],
       [-0.30980682,  1.75709867]], dtype=float32)

In [16]:
dh = tf.matmul(d, h)
dh.eval()

array([[-5.95834017,  2.22311735],
       [-5.95834017,  2.22311735]], dtype=float32)